type Env = { DB: D1Database; EVIDENCE: R2Bucket; ENVIRONMENT: string; ALLOWED_ORIGIN: string };
const domains=new Set(['Governance','Risk','Controls','Evidence','Compliance','Resilience']);
const severities=new Set(['low','moderate','high','critical']);
const types=new Set(['evidence','threat','finding','telemetry']);
const json=(data:unknown,status=200,origin='https://gavinlujan.com')=>Response.json(data,{status,headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Content-Type, CF-Access-Authenticated-User-Email, X-Tenant-ID','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store'}});
function context(req:Request){const tenant=(req.headers.get('X-Tenant-ID')||'public-demo').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,64);const actor=req.headers.get('CF-Access-Authenticated-User-Email')||'anonymous';return{tenant,actor}}
async function audit(env:Env,tenant:string,actor:string,action:string,objectType:string,objectId:string|null,detail:unknown){await env.DB.prepare('INSERT INTO audit_log(id,tenant_id,actor,action,object_type,object_id,detail) VALUES(?1,?2,?3,?4,?5,?6,?7)').bind(crypto.randomUUID(),tenant,actor,action,objectType,objectId,JSON.stringify(detail)).run()}
async function ensureTenant(env:Env,id:string){await env.DB.prepare('INSERT OR IGNORE INTO tenants(id,name) VALUES(?1,?2)').bind(id,id).run()}
async function dashboard(env:Env,tenant:string){const [signals,findings,snaps,controls]=await Promise.all([env.DB.prepare('SELECT type,domain,severity,title,source,confidence,created_at FROM signals WHERE tenant_id=?1 ORDER BY created_at DESC LIMIT 100').bind(tenant).all(),env.DB.prepare("SELECT id,domain,title,severity,status,due_at,created_at FROM findings WHERE tenant_id=?1 AND status!='closed' ORDER BY created_at DESC LIMIT 100").bind(tenant).all(),env.DB.prepare('SELECT risk_score,control_confidence,created_at FROM risk_snapshots WHERE tenant_id=?1 ORDER BY created_at DESC LIMIT 30').bind(tenant).all(),env.DB.prepare('SELECT domain,maturity,evidence_confidence FROM controls WHERE tenant_id=?1').bind(tenant).all()]);return{signals:signals.results,findings:findings.results,history:snaps.results,controls:controls.results}}
async function ingest(req:Request,env:Env,tenant:string,actor:string){const body=await req.json() as Record<string,unknown>;const type=String(body.type||'telemetry').toLowerCase(),domain=String(body.domain||'Risk'),severity=String(body.severity||'moderate').toLowerCase(),title=String(body.title||'Untitled signal').slice(0,300),source=String(body.source||'API').slice(0,120),confidence=Math.max(0,Math.min(100,Number(body.confidence)||70));if(!types.has(type)||!domains.has(domain)||!severities.has(severity))return json({error:'invalid signal taxonomy'},400,env.ALLOWED_ORIGIN);const id=crypto.randomUUID(),payloadKey=`${tenant}/signals/${new Date().toISOString().slice(0,10)}/${id}.json`;await env.EVIDENCE.put(payloadKey,JSON.stringify(body),{httpMetadata:{contentType:'application/json'}});await env.DB.prepare('INSERT INTO signals(id,tenant_id,type,domain,severity,title,source,confidence,payload_key) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)').bind(id,tenant,type,domain,severity,title,source,confidence,payloadKey).run();if(type==='finding'){await env.DB.prepare('INSERT INTO findings(id,tenant_id,domain,title,severity,status) VALUES(?1,?2,?3,?4,?5,?6)').bind(crypto.randomUUID(),tenant,domain,title,severity,'open').run()}await audit(env,tenant,actor,'ingest','signal',id,{type,domain,severity,source});return json({ok:true,id},201,env.ALLOWED_ORIGIN)}
async function snapshot(env:Env,tenant:string,actor='scheduler'){const sig=await env.DB.prepare("SELECT severity,confidence,type FROM signals WHERE tenant_id=?1 AND created_at >= datetime('now','-30 days')").bind(tenant).all<Record<string,unknown>>();const ctl=await env.DB.prepare('SELECT maturity,evidence_confidence FROM controls WHERE tenant_id=?1').bind(tenant).all<Record<string,unknown>>();const weight:Record<string,number>={low:4,moderate:9,high:16,critical:25};let threat=0,evidence=0;for(const s of sig.results){const c=Number(s.confidence)/100;if(s.type==='evidence')evidence+=c;else if(s.type==='threat'||s.type==='finding')threat+=(weight[String(s.severity)]||9)*c}const maturity=ctl.results.length?ctl.results.reduce((a,x)=>a+Number(x.maturity),0)/(ctl.results.length*5):.5;const conf=ctl.results.length?Math.round(ctl.results.reduce((a,x)=>a+Number(x.evidence_confidence),0)/(ctl.results.length*100)*100):Math.min(100,Math.round(50+evidence));const risk=Math.max(0,Math.min(100,Math.round((1-maturity)*65+threat/5-evidence)));const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO risk_snapshots(id,tenant_id,risk_score,control_confidence) VALUES(?1,?2,?3,?4)').bind(id,tenant,risk,conf).run();await audit(env,tenant,actor,'snapshot','risk',id,{risk,conf});return{risk,conf}}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url),{tenant,actor}=context(req);if(req.method==='OPTIONS')return new Response(null,{headers:{'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN,'Access-Control-Allow-Headers':'Content-Type, CF-Access-Authenticated-User-Email, X-Tenant-ID','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}});try{await ensureTenant(env,tenant);if(url.pathname==='/api/health')return json({ok:true,service:'ziawolf-grc-api',environment:env.ENVIRONMENT},200,env.ALLOWED_ORIGIN);if(url.pathname==='/api/dashboard'&&req.method==='GET')return json(await dashboard(env,tenant),200,env.ALLOWED_ORIGIN);if(url.pathname==='/api/signals'&&req.method==='POST')return await ingest(req,env,tenant,actor);if(url.pathname==='/api/snapshot'&&req.method==='POST')return json(await snapshot(env,tenant,actor),201,env.ALLOWED_ORIGIN);if(url.pathname==='/api/audit'&&req.method==='GET'){const r=await env.DB.prepare('SELECT actor,action,object_type,object_id,detail,created_at FROM audit_log WHERE tenant_id=?1 ORDER BY created_at DESC LIMIT 200').bind(tenant).all();return json(r.results,200,env.ALLOWED_ORIGIN)}return json({error:'not found'},404,env.ALLOWED_ORIGIN)}catch(error){console.error(JSON.stringify({event:'request_error',path:url.pathname,error:String(error)}));return json({error:'internal error'},500,env.ALLOWED_ORIGIN)}},async scheduled(controller:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil((async()=>{const tenants=await env.DB.prepare('SELECT id FROM tenants').all<{id:string}>();for(const t of tenants.results)await snapshot(env,t.id)})())}};
